name: Auto Blog HTML Generator

on:
  workflow_dispatch:     

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" > .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "PIXELS_API=${{ secrets.PIXELS_API }}" >> .env

      - name: Run blog generation script
        run: bash run.sh

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add --all
          git commit -m "Auto-publish blog HTML and report [$(date)]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
